# Pandas Subsetting

In [1]:
import pandas as pd

# Read in file, argument is the file path
df = pd.read_csv('data/wetlands_seasonal_bird_diversity.csv')

In [ ]:
# View first five rows
df.head()

,year,CSM_winter,CSM_spring,CSM_fall,MUL_winter,MUL_spring,MUL_fall,SDW_winter,SDW_spring,SDW_fall,TJE_winter,TJE_spring,TJE_fall
0,2010,39.0,40.0,50.0,45.0,NaN,61.0,NaN,75.0,85.0,NaN,NaN,81.0
1,2011,48.0,44.0,NaN,58.0,52.0,NaN,78.0,74.0,NaN,67.0,70.0,NaN
2,2012,51.0,43.0,49.0,57.0,58.0,53.0,71.0,72.0,73.0,70.0,63.0,69.0
3,2013,42.0,46.0,38.0,60.0,58.0,62.0,69.0,70.0,70.0,69.0,74.0,64.0
4,2014,38.0,43.0,45.0,49.0,52.0,57.0,61.0,78.0,71.0,60.0,81.0,62.0

In [ ]:
# View datatypes of columns
df.dtypes

year            int64
CSM_winter    float64
CSM_spring    float64
CSM_fall      float64
MUL_winter    float64
MUL_spring    float64
MUL_fall      float64
SDW_winter    float64
SDW_spring    float64
SDW_fall      float64
TJE_winter    float64
TJE_spring    float64
TJE_fall      float64
dtype: object

## By Columns

### A single column

In [ ]:
# Select mul_spring column from df
mul_spring = df['MUL_spring']

# Print object typ
print(type(mul_spring))

<class 'pandas.core.series.Series'>

### Multiple columns

In [8]:
tje_wf = df[['TJE_winter', 'TJE_fall']]

print(tje_wf.head())
print(type(tje_wf))

   TJE_winter  TJE_fall
0         NaN      81.0
1        67.0       NaN
2        70.0      69.0
3        69.0      64.0
4        60.0      62.0
<class 'pandas.core.frame.DataFrame'>

### With slice

`.loc[]`: inclusive on both sides of []

In [14]:
csm_mul = df.loc[:, 'CSM_winter':'MUL_fall']
# Print original df head
print(df.columns)
# Print sliced head
print(csm_mul.columns)

Index(['year', 'CSM_winter', 'CSM_spring', 'CSM_fall', 'MUL_winter',
       'MUL_spring', 'MUL_fall', 'SDW_winter', 'SDW_spring', 'SDW_fall',
       'TJE_winter', 'TJE_spring', 'TJE_fall'],
      dtype='object')
Index(['CSM_winter', 'CSM_spring', 'CSM_fall', 'MUL_winter', 'MUL_spring',
       'MUL_fall'],
      dtype='object')

## By Rows

### By a condition

In [19]:
post_2020 = df[df['year'] > 2020]
post_2020.head()

,year,CSM_winter,CSM_spring,CSM_fall,MUL_winter,MUL_spring,MUL_fall,SDW_winter,SDW_spring,SDW_fall,TJE_winter,TJE_spring,TJE_fall
11,2021,47.0,44.0,53.0,54.0,55.0,60.0,57.0,58.0,57.0,53.0,68.0,51.0
12,2022,40.0,46.0,49.0,60.0,55.0,65.0,57.0,60.0,57.0,60.0,61.0,60.0
13,2023,56.0,43.0,36.0,72.0,59.0,53.0,64.0,63.0,33.0,60.0,56.0,38.0

In [37]:
subset0 = df[df['SDW_spring'] >= 75]
subset0

,year,CSM_winter,CSM_spring,CSM_fall,MUL_winter,MUL_spring,MUL_fall,SDW_winter,SDW_spring,SDW_fall,TJE_winter,TJE_spring,TJE_fall
0,2010,39.0,40.0,50.0,45.0,NaN,61.0,NaN,75.0,85.0,NaN,NaN,81.0
4,2014,38.0,43.0,45.0,49.0,52.0,57.0,61.0,78.0,71.0,60.0,81.0,62.0

`.between()`

- **don't use `.loc()`** for "slicing" rows

In [20]:
subset = df[df['year'].between(2016, 2020)]
subset.head()

,year,CSM_winter,CSM_spring,CSM_fall,MUL_winter,MUL_spring,MUL_fall,SDW_winter,SDW_spring,SDW_fall,TJE_winter,TJE_spring,TJE_fall
6,2016,41.0,36.0,47.0,63.0,48.0,58.0,67.0,62.0,57.0,76.0,76.0,58.0
7,2017,46.0,41.0,43.0,57.0,54.0,53.0,66.0,45.0,54.0,72.0,63.0,57.0
8,2018,48.0,48.0,44.0,56.0,54.0,57.0,55.0,49.0,51.0,66.0,60.0,55.0
9,2019,39.0,39.0,40.0,57.0,52.0,53.0,54.0,55.0,53.0,63.0,54.0,50.0
10,2020,46.0,NaN,47.0,56.0,NaN,66.0,57.0,NaN,58.0,54.0,40.0,54.0

### By multiple conditions

In [21]:
df[(df['CSM_winter'] > 50) | (df['CSM_fall'] > 50)]

,year,CSM_winter,CSM_spring,CSM_fall,MUL_winter,MUL_spring,MUL_fall,SDW_winter,SDW_spring,SDW_fall,TJE_winter,TJE_spring,TJE_fall
2,2012,51.0,43.0,49.0,57.0,58.0,53.0,71.0,72.0,73.0,70.0,63.0,69.0
11,2021,47.0,44.0,53.0,54.0,55.0,60.0,57.0,58.0,57.0,53.0,68.0,51.0
13,2023,56.0,43.0,36.0,72.0,59.0,53.0,64.0,63.0,33.0,60.0,56.0,38.0

In [30]:
df[(df['CSM_spring'] > 30) & (df['CSM_fall'] > 45)]

,year,CSM_winter,CSM_spring,CSM_fall,MUL_winter,MUL_spring,MUL_fall,SDW_winter,SDW_spring,SDW_fall,TJE_winter,TJE_spring,TJE_fall
0,2010,39.0,40.0,50.0,45.0,NaN,61.0,NaN,75.0,85.0,NaN,NaN,81.0
2,2012,51.0,43.0,49.0,57.0,58.0,53.0,71.0,72.0,73.0,70.0,63.0,69.0
6,2016,41.0,36.0,47.0,63.0,48.0,58.0,67.0,62.0,57.0,76.0,76.0,58.0
11,2021,47.0,44.0,53.0,54.0,55.0,60.0,57.0,58.0,57.0,53.0,68.0,51.0
12,2022,40.0,46.0,49.0,60.0,55.0,65.0,57.0,60.0,57.0,60.0,61.0,60.0

### By position

`.iloc()`

In [35]:
df.iloc[6:8]

,year,CSM_winter,CSM_spring,CSM_fall,MUL_winter,MUL_spring,MUL_fall,SDW_winter,SDW_spring,SDW_fall,TJE_winter,TJE_spring,TJE_fall
6,2016,41.0,36.0,47.0,63.0,48.0,58.0,67.0,62.0,57.0,76.0,76.0,58.0
7,2017,46.0,41.0,43.0,57.0,54.0,53.0,66.0,45.0,54.0,72.0,63.0,57.0

## By Columns & Rows

### By conditions

`df.loc[row-selection , column-selection]`

In [45]:
df.loc[df['year'] > 2020, ['MUL_winter','MUL_spring', 'MUL_fall']]

    MUL_winter  MUL_spring  MUL_fall
11        54.0        55.0      60.0
12        60.0        55.0      65.0
13        72.0        59.0      53.0

### By positions

`df.iloc[row-indices, column-indices`]

- *row-indices*: **slice** of integer indices using `:`

- *column-indices*: **list** of integer indices using `,`

In [47]:
df.iloc[6:8, [6,7]]

   MUL_fall  SDW_winter
6      58.0        67.0
7      53.0        66.0