# Pandas Intro

In [1]:
import pandas as pd
import numpy as np

## Series Check-in

The integer number -999 is often used to represent missing values. Create a `pandas.Series` named `s` with four integer values, two of which are -999. The index of this series should be the the letters A through D.

In [9]:
s = pd.Series([-999, -999, 67, 41], index=['A', 'B', 'C', 'D'])
print(s)

A   -999
B   -999
C     67
D     41
dtype: int64

Use the `mask()` method to update the series `s` so that the -999 values are replaced by NA values. HINT: check the first example in the method’s documentation.

In [12]:
s.mask(s == -999, inplace=True)
print(s)

A     NaN
B     NaN
C    67.0
D    41.0
dtype: float64

## Dataframes Check-in

Update the column names to C1 and C2 by updating the `df.columns` attribute.

In [13]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [17]:
df.columns = ['C1', 'C2']
df

   C1   C2
0   0  3.1
1   1  3.2
2   2  3.3

## Lesson Summary:

- np arrays and pd series are similar but series have a dedicated index

- series' indexes can be customized

- dataframes are just multiple series & can also have an index